version: "3.0"
services:
  spark-master:
    image: spark-master:2.4.4
    container_name: spark-master
    hostname: spark-master
    ports:
      - "5080:8080"
      - "7077:7077"
      - "5050:8081"
    networks: 
      spark-network:
        ipv4_address: 10.5.0.2
    volumes:
       - ./samples/source:/opt/spark-apps
       - ./samples/data:/opt/spark-data
    environment:
      - "SPARK_LOCAL_IP=spark-master"
  spark-worker-1:
    image: spark-worker:2.4.4
    container_name: spark-worker-1
    hostname: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "5081:8081"
    env_file: ./env/spark-worker.sh
    environment:
      - "SPARK_LOCAL_IP=spark-worker-1"
    networks: 
      spark-network:
        ipv4_address: 10.5.0.3
    volumes:
       - ./samples/source:/opt/spark-apps
       - ./samples/data:/opt/spark-data
  spark-worker-2:
    image: spark-worker:2.4.4
    container_name: spark-worker-2
    hostname: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "5082:8081"
    env_file: ./env/spark-worker.sh
    environment:
      - "SPARK_LOCAL_IP=spark-worker-2"
    networks: 
      spark-network:
        ipv4_address: 10.5.0.4
    volumes:
       - ./samples/source:/opt/spark-apps
       - ./samples/data:/opt/spark-data
  spark-worker-3:
    image: spark-worker:2.4.4
    container_name: spark-worker-3
    hostname: spark-worker-3
    depends_on:
      - spark-master
    ports:
      - "5083:8081"
    env_file: ./env/spark-worker.sh
    environment:
      - "SPARK_LOCAL_IP=spark-worker-3"
    networks: 
      spark-network:
        ipv4_address: 10.5.0.5
    volumes:
       - ./samples/source:/opt/spark-apps
       - ./samples/data:/opt/spark-data

networks:
  spark-network:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 10.5.0.0/16
